@startuml

hide circle
hide stereotype
hide empty members

class Usuario
class Token
class Mercado
class Precio
class Direccion
class Entidad
class Operacion
class Temporalidad
class AlertaPrecio
class Webhook
class Notificacion

Usuario "1" -- "*" Entidad : crea
Usuario "1" -- "*" AlertaPrecio : configura
Entidad "1" -- "*" Direccion : agrupa
Direccion "1" -- "*" Operacion : ejecuta
Operacion "*" -- "1" Token : sobre
Token "*" -- "1" Mercado : pertenece-a
Token "1" -- "1" Precio : tiene
AlertaPrecio "*" -- "1" Token : monitoriza
AlertaPrecio "1" -- "1" Webhook : notifica-via
AlertaPrecio "1" -- "*" Notificacion : genera

note "Spot | PerpNativo | PerpHIP3" as N1
N1 .. Mercado

note "1h | 4h | 6h | 12h | 1d | 1w" as N2
N2 .. Temporalidad

@enduml
