@startsalt
{+
  <b>Entidades
  ---
  Filtrar: | "                              "
  ---
  {#
    <b>Nombre        | <b>N.º direcciones | <b>Acciones
    Wintermute     | 12                 | [Abrir] [Eliminar]
    Jump Trading   | 7                  | [Abrir] [Eliminar]
    Cumberland     | 4                  | [Abrir] [Eliminar]
  }
  ---
  [Crear entidad] | [Volver]
}
@endsalt
