@startsalt

{+
  {/ Leaderboard | Entidades | <b>Alertas }
  {
    {+
      <b>Alertas configuradas
      ---
      {#
        <b>Token | <b>Mercado | <b>Umbral ($) | <b>Webhook | <b>Estado | <b>Acciones
        BTC | PerpNativo | 100 000 | https://discord... | Activa | [Desactivar] [Eliminar]
        PURR | Spot | 0.50 | https://discord... | Activa | [Desactivar] [Eliminar]
        FRIEND | PerpHIP3 | 2.00 | https://slack... | Desactivada | [Activar] [Eliminar]
      }
    }
    ---
    {+
      <b>Crear nueva alerta
      ---
      Mercado: | ^Spot ^ PerpNativo ^ PerpHIP3^
      Token: | ^BTC^
      Umbral ($): | "          "
      URL Webhook: | "                              "
      ---
      [Crear alerta]
    }
  }
}

@endsalt
