@startsalt
{+
  <b>Alertas de precio
  ---
  Filtrar: | "                              "
  ---
  {#
    <b>Token | <b>Mercado     | <b>Umbral ($) | <b>Webhook          | <b>Estado     | <b>Acciones
    BTC   | Perp nativo    | 100.000    | https://discord...  | Operativa    | [Abrir] [Eliminar]
    PURR  | Spot           | 0,50       | https://discord...  | Operativa    | [Abrir] [Eliminar]
    FRIEND| Perp HIP-3     | 2,00       | https://slack...    | Notif.fallida| [Abrir] [Eliminar]
  }
  ---
  [Crear alerta] | [Volver]
}
@endsalt
