@startsalt

{+
  {/ <b>Leaderboard | Entidades | Alertas }
  {
    {+
      <b>Spot (HIP-1 / HIP-2)
      ---
      Token: | ^PURR^
      Temporalidad: | ^1h ^ 4h ^ 6h ^ 12h ^ 1d ^ 1w^
      {#
        <b>Pos | <b>Direccion / Entidad | <b>Vol. compra ($) | <b>Vol. venta ($)
        1 | Wintermute | 1 200 000 | 340 000
        2 | 0xabc1...f3 | 890 000 | 120 000
        3 | 0x9ef4...b2 | 540 000 | 780 000
      }
    }
    ---
    {+
      <b>Perps nativos
      ---
      Token: | ^BTC^
      Temporalidad: | ^1h ^ 4h ^ 6h ^ 12h ^ 1d ^ 1w^
      {#
        <b>Pos | <b>Direccion / Entidad | <b>Vol. compra ($) | <b>Vol. venta ($)
        1 | 0xdef2...a7 | 3 400 000 | 1 200 000
        2 | Wintermute | 2 100 000 | 900 000
        3 | 0x7bc3...e1 | 1 800 000 | 2 300 000
      }
    }
    ---
    {+
      <b>Perps HIP-3
      ---
      Token: | ^FRIEND^
      Temporalidad: | ^1h ^ 4h ^ 6h ^ 12h ^ 1d ^ 1w^
      {#
        <b>Pos | <b>Direccion / Entidad | <b>Vol. compra ($) | <b>Vol. venta ($)
        1 | 0x12a5...c8 | 450 000 | 60 000
        2 | 0xfed1...99 | 320 000 | 180 000
        3 | 0x88b2...d4 | 210 000 | 290 000
      }
    }
  }
}

@endsalt
